apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: queue
  name: queue
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: queue
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/laravel-complete-dockerization-default: "true"
        io.kompose.service: queue
    spec:
      containers:
        - env:
            - name: APP_ENV
            - name: CONTAINER_ROLE
              value: queue
          image: queue
          name: queue
          resources: {}
          volumeMounts:
            - mountPath: /var/www
              name: queue-claim0
          workingDir: /var/www
      restartPolicy: Always
      volumes:
        - name: queue-claim0
          persistentVolumeClaim:
            claimName: queue-claim0
status: {}
