apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: websocket
  name: websocket
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: websocket
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/laravel-complete-dockerization-default: "true"
        io.kompose.service: websocket
    spec:
      containers:
        - env:
            - name: APP_ENV
            - name: CONTAINER_ROLE
              value: websocket
          image: websocket
          name: websocket
          ports:
            - containerPort: 6001
              hostPort: 6001
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /var/www
              name: websocket-claim0
          workingDir: /var/www
      restartPolicy: Always
      volumes:
        - name: websocket-claim0
          persistentVolumeClaim:
            claimName: websocket-claim0
status: {}
